export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  header,
  footer,

 
    
}: {
  children: React.ReactNode;
  footer:React.ReactNode;
  header:React.ReactNode;
}) {
  return (
    <>
   <div className="flex w-full flex-col items-center gap-[13px] bg-gray-300_07">
        <div className="mx-auto flex w-full max-w-[99%] flex-col gap-[9px] md:p-5">
           {header}
           {children}
       
       </div>
    </div>
          {footer}
    </>
  )
}