export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  footer,
 
    
}: {
  children: React.ReactNode;
  footer:React.ReactNode;
}) {
  return (
    <>
       {children}
        {footer}
    </>
  )
}
