export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  product,
  inbox,
  orderlist,
  productinstock,


 
    
}: {
  children: React.ReactNode;
  product:React.ReactNode;
  inbox :React.ReactNode;
  orderlist:React.ReactNode;
  productinstock:React.ReactNode;

}) {
  return (
    <html>
        <body>
             {productinstock}
        </body>


    </html>
  )
}