import { Heading } from "./heading";
import {Text} from "./text";
import { TextArea } from "./textarea";
import { Button} from "./button";
import { Img } from "./img";
import { Input } from "./input";
import { SelectBox } from "./selectbox";
import { CheckBox } from "./checkbox";
import { RatingBar } from "./ratingbar";
import {Slider}from "./slider";
export { Heading, Button, Img, Input, SelectBox,Text,TextArea, CheckBox,RatingBar,Slider};
